apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-b
  labels:
    app: api-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-b
  template:
    metadata:
      labels:
        app: api-b
    spec:
      containers:
        - name: api-b
          image: mizok/api-b:latest
          env:
            - name: API_A_URL
              value: "http://api-a-service:8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-b-service
spec:
  selector:
    app: api-b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
