apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-a
  labels:
    app: api-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-a
  template:
    metadata:
      labels:
        app: api-a
    spec:
      containers:
        - name: api-a
          image: mizok/api-a:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-a-service
spec:
  selector:
    app: api-a
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
